pipeline {
    agent any

    options {
        timestamps()
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '20'))
        skipDefaultCheckout(true)
    }

    parameters {
        string(name: 'APP_NAME', defaultValue: 'flask-release-demo')
        string(name: 'RELEASE_VERSION', defaultValue: '1.0.0')

        string(name: 'EMAIL_TO', defaultValue: 'projectworkuser@gmail.com')
        booleanParam(name: 'PUBLISH_EMAIL', defaultValue: true)
        booleanParam(name: 'PUBLISH_TO_GITHUB', defaultValue: true)
        booleanParam(name: 'PUBLISH_TO_CONFLUENCE', defaultValue: true)

        string(name: 'RELEASE_NOTE_PATH',
            defaultValue: 'C:\\Users\\I17270834\\Downloads\\Release_Notes_v1.0.0.pdf')

        string(name: 'CONFLUENCE_BASE_URL',
            defaultValue: 'https://projectworkuser.atlassian.net/wiki')

        string(name: 'CONFLUENCE_SPACE_KEY', defaultValue: 'DEMO')
        string(name: 'CONFLUENCE_PARENT_PAGE_ID', defaultValue: '131214')

        string(name: 'GITHUB_OWNER', defaultValue: 'pjwrkusr')
        string(name: 'GITHUB_REPO', defaultValue: 'flask-demo-publish-docs')
    }

    environment {
        RELEASE_NOTES_DIR = "release-notes"
        DIST_DIR = "dist"

        RELEASE_NOTES_ZIP = "${params.APP_NAME}-${params.RELEASE_VERSION}-release-notes.zip"
        BINARIES_ZIP = "${params.APP_NAME}-${params.RELEASE_VERSION}-deployment-binaries.zip"

        CONFLUENCE_URL = "${params.CONFLUENCE_BASE_URL}"
        CONFLUENCE_SPACE = "${params.CONFLUENCE_SPACE_KEY}"
        CONFLUENCE_PARENT_ID = "${params.CONFLUENCE_PARENT_PAGE_ID}"

        GH_OWNER = "${params.GITHUB_OWNER}"
        GH_REPO = "${params.GITHUB_REPO}"

        CONFLUENCE_CREDS = credentials('confluence-projectwork-token')
        GH_TOKEN = credentials('github-token-release')
    }

    stages {

        stage('Checkout') {
            steps { checkout scm }
        }

        stage('Prepare folders') {
            steps {
                powershell '''
                New-Item -ItemType Directory -Force -Path $env:RELEASE_NOTES_DIR | Out-Null
                New-Item -ItemType Directory -Force -Path $env:DIST_DIR | Out-Null
                '''
            }
        }

        stage('Prepare files') {
            steps {
                powershell '''
                Copy-Item "$env:RELEASE_NOTE_PATH" "$env:RELEASE_NOTES_DIR"

                Compress-Archive -Path "$env:RELEASE_NOTES_DIR\\*" `
                    -DestinationPath "$env:DIST_DIR\\$env:RELEASE_NOTES_ZIP" -Force

                "demo binary" | Out-File "$env:DIST_DIR\\dummy.txt"
                Compress-Archive -Path "$env:DIST_DIR\\dummy.txt" `
                    -DestinationPath "$env:DIST_DIR\\$env:BINARIES_ZIP" -Force
                '''
            }
        }

        stage('Publish to GitHub') {
            when { expression { params.PUBLISH_TO_GITHUB } }
            steps {
                powershell '''
                $headers = @{
                    Authorization = "Bearer $env:GH_TOKEN"
                    Accept = "application/vnd.github+json"
                }

                $releaseApi = "https://api.github.com/repos/$env:GH_OWNER/$env:GH_REPO/releases"
                $tag = $env:RELEASE_VERSION

                try {
                    $release = Invoke-RestMethod -Method Post -Uri $releaseApi -Headers $headers `
                        -Body (@{
                            tag_name = $tag
                            name = $tag
                        } | ConvertTo-Json)
                } catch {
                    $release = Invoke-RestMethod -Uri "$releaseApi/tags/$tag" -Headers $headers
                }

                $uploadUrl = $release.upload_url -replace "\\{.*", ""

                Get-ChildItem "$env:DIST_DIR\\*.zip" | ForEach-Object {
                    $file = $_.FullName
                    $name = $_.Name
                    $url = "$uploadUrl?name=$name"

                    Invoke-RestMethod -Method Post -Uri $url -Headers $headers `
                        -InFile $file -ContentType "application/zip"

                    Write-Host "Uploaded $name"
                }
                '''
            }
        }

        stage('Publish to Confluence') {
            when { expression { params.PUBLISH_TO_CONFLUENCE } }
            steps {
                powershell '''
                $pair = "$env:CONFLUENCE_CREDS_USR`:$env:CONFLUENCE_CREDS_PSW"
                $bytes = [Text.Encoding]::ASCII.GetBytes($pair)
                $auth = [Convert]::ToBase64String($bytes)

                $bodyHtml = "<h1>$env:APP_NAME $env:RELEASE_VERSION</h1><p>Generated by Jenkins</p>"

                $payload = @{
                    type="page"
                    title="$env:APP_NAME $env:RELEASE_VERSION"
                    space=@{key=$env:CONFLUENCE_SPACE}
                    body=@{
                        storage=@{
                            value=$bodyHtml
                            representation="storage"
                        }
                    }
                }

                if ($env:CONFLUENCE_PARENT_ID) {
                    $payload.ancestors = @(@{id=$env:CONFLUENCE_PARENT_ID})
                }

                $resp = Invoke-RestMethod `
                    -Uri "$env:CONFLUENCE_URL/rest/api/content" `
                    -Method Post `
                    -Headers @{Authorization="Basic $auth";"Content-Type"="application/json"} `
                    -Body ($payload | ConvertTo-Json -Depth 10)

                $pageId = $resp.id
                Write-Host "Created page $pageId"

                Get-ChildItem "$env:DIST_DIR\\*.zip" | ForEach-Object {
                    curl.exe -u "$env:CONFLUENCE_CREDS_USR`:$env:CONFLUENCE_CREDS_PSW" `
                        -H "X-Atlassian-Token: nocheck" `
                        -F "file=@$($_.FullName)" `
                        "$env:CONFLUENCE_URL/rest/api/content/$pageId/child/attachment"

                    Write-Host "Uploaded $($_.Name)"
                }
                '''
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'dist/*.zip'
        }
    }
}